image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python@2020.9.114305:8LrOitPaJsLgMYQ7e3G62g==

ports:
  - port: 8080
    onOpen: open-preview
  - port: 8888
    onOpen: open-browser